\LoadClass[11pt,a4paper,serif]{moderncv}
% fontsize,papersize,font
% a4, a5, b5, legalpaper, executivepaper, landscape

% moderncv themes
\moderncvstyle{banking} % style options are 'casual' (default), 'classic', 'oldstyle' and 'banking'
\moderncvcolor{blue}% color options 'blue' (default), 'orange', 'green', 'red', 'purple', 'grey' and 'black'


% personal data
\name{Pavan}{Naidu}
\title{Resume} % optional, remove / comment the line if not wanted
\address{43 Gokulam Park Road, V.V.Mohalla}{Mysore, Karnataka, 570002}{India}% optional,
\phone[mobile]{+91 9742538842} % optional, remove / comment the line if not wanted
\email{pavan1101naidu@gmail.com} % optional, remove / comment the line if not wanted
%\homepage{ajnorton.com} % optional, remove / comment the line if not wanted
\social[github][github.com/pavannaidu]{pavannaidu}
\social[linkedin][in.linkedin.com/in/pavannaidu]{pavannaidu} %twitter




%\renewcommand{\familydefault}{\rmdefaul­t} % to set the default font; use '\sfdefault' for the default sans serif font, '\rmdefault' for the default roman one, or any tex font name
\nopagenumbers{} % uncomment to suppress automatic page numbering for CVs longer than one page


% character encoding
\RequirePackage[utf8]{inputenc}
\RequirePackage{geometry} % changes margins across the page
\geometry{
left=15mm,
right=15mm,
top=15mm,
bottom=15mm,
}

\RequirePackage{fontawesome}
